### ISSUE TITLE
Latest `opensanctions` codebase and docker image seem to be out of sync with the currently published documentation

### ISSUE THREAD

**Issue by ppseprus** [opensanctions/opensanctions#190]
**Background**
I've been using `opensanctions` for a couple months now, trying to build on top of it. I had a working setup based on `356e1a2`, but when another person tried to check out my work, he started receiving the following error:
```py
$ docker-compose run --rm app opensanctions run sanctions
Creating opensanctions_app_run ... done
Traceback (most recent call last):
  File "/usr/local/bin/opensanctions", line 33, in <module>
    sys.exit(load_entry_point('opensanctions', 'console_scripts', 'opensanctions')())
  File "/usr/local/bin/opensanctions", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opensanctions/opensanctions/cli.py", line 11, in <module>
    from opensanctions.core import Dataset, Context, setup
  File "/opensanctions/opensanctions/core/__init__.py", line 3, in <module>
    from opensanctions.core.dataset import Dataset
  File "/opensanctions/opensanctions/core/dataset.py", line 10, in <module>
    from opensanctions.core.db import KEY_LEN
  File "/opensanctions/opensanctions/core/db.py", line 17, in <module>
    assert (
AssertionError: Need to configure $OPENSANCTIONS_DATABASE_URI.
ERROR: 1
```

I've tried creating a `.env`, configuring the missing variable — unfortunately with no luck.
```ini
OPENSANCTIONS_DATABASE_URI=sqlite:///data/state/opensanctions.sqlite
```

I've tried checking back to the previous commit and the `production` branch, but both resulted in the same error. I suspect due to the fact that I have manually removed the previous docker images.

I now believe that later versions of the codebase (than the above commit), as well as the related `pudo/opensanctions` docker image are out of sync with the currently published [documentations](https://docs.opensanctions.org/en/latest/install.html).

As a result, I cannot run `opensanctions`.

**Steps to Reproduce**
**1.** Checkout the repository to a clean environment (no existing docker image or container)
This commit in particular `2cb9b7f0e9a404ebb67094c9840f1033c2f3a002` 
The `pudo/opensanctions` image that was last updated on **Jan 26th, 2022 at 1:21 am**.

**A)**
**2.** Run `make build`
**3.** Run `docker-compose run --rm app opensanctions run sanctions`

**B)**
**2.** Run `make all`

**Expected Outcome**
OpenSanctions is up and running, and in case of **A**, the `sanctions` collection is pulled and normalised.

**Actual Outcome**
The above error is received.

**Versions**
Python 2.7.18
Docker version 20.10.12, build e91ed57
macOS Monterey Version 12.1

----

Could you please, help me figure this out? What am I missing?
Thanks!

**Comment by ppseprus** [comment]
<img width="693" alt="Screenshot 2022-01-26 at 18 36 44" src="https://user-images.githubusercontent.com/1323285/151221096-2165ac21-b4d1-4a63-a444-66d2d8ad0f2f.png">

**Comment by pudo** [comment]
Hi @ppseprus, thanks for this well-crafted issue report and pointing out the disparity between the documentation and the current codebase. What's happened is this: the row count in our statement table has exceeded 5mn, and I also decided to move the HTTP response caching mechanism into the same SQL database. Together, these two changes ended up making it impractical to keep using SQLite as a backend. This irks me, because I liked the flat-file-y-ness of the whole setup.

In any case, you now have to set a PostgreSQL database in `$OPENSANCTIONS_DATABASE_URI`, like this: `postgresql://localhost/opensanctions`. The schema will be created automatically, and the first run might take a long time as it needs to fill the request cache for all the Wikidata collections. 

btw feel free to [hang out in Slack](https://join.slack.com/t/opensanctions/shared_invite/zt-xwnzvht1-9jPnHUwfCzW_Yw9MAG6vTA) to discuss further. 

I'll leave this issue open as a reminder to update the documentation.

**Comment by ppseprus** [comment]
Hey @pudo! Thanks for the quick response! :)
