### ISSUE TITLE
include a "total" download

### ISSUE THREAD

**Issue by VladimirAlexiev** [opensanctions/opensanctions#199]
https://www.opensanctions.org/datasets/ shows 4 collections and 44 datasets.
* The biggest collection "Due Diligence List" https://www.opensanctions.org/datasets/default/ includes 42 datasets.
I don't know which 2 are missing from it
* Please include a pseudo-collection "all" to allow download of all of your data
 (eg for the purpose of linking it to WD)

**Comment by pudo** [comment]
You can navigate to `all` here: https://www.opensanctions.org/datasets/all/  - I don't want to include it in the UI because the data that isn't there is data that should be consumed with extreme care - e.g. search notices for missing children, and the Russian sanctions list, which is used to criminalise the opposition in the country. Publishing the `all` collection in the UI would inevitably lead to everybody fetching that - and then complaining a little while later when they discover Joe Biden is now a wanted criminal.

**Comment by VladimirAlexiev** [comment]
Thanks @pudo! 
And you've answered my questions at https://www.wikidata.org/wiki/Wikidata:Property_proposal/OpenSanctions_ID: none of these lists belong to WD:
- Russian terrorists & extremists list. "it's nutty": these are opposition activists and journalists
- INTERPOL missing children (Yellow Notices): ok, maybe this doesn't belong in WD (for privacy reasons)
